package by.newnet.command;

public enum CommandName {
	AUTHENTICATION, 
	REGISTRATION,
	CHECK_ACCOUNT,
	ADD_NEW_CONTRACT,
	LOG_OUT,
	CHANGE_LOCALE,
	SHOW_REQUESTS,
	POST_REQUEST,
	SHOW_ACCOUNT_INFO,
	CHANGE_PERSONAL_DETAILS,
	SET_PASSWORD,
	SET_CONTACTS,
	SHOW_TARIFFS,
	SHOW_USERS,
	SHOW_OPERATIONS,
	SUBSCRIBE,
	TO_PAYMENT,
	PAY,
	SAVE_TARIFF,
	BLOCK_USER,
	POST_NEWS
	}
