package by.newnet.command;

/**
 * The Enum CommandName.
 */
public enum CommandName {
	AUTHENTICATION,
	TO_REGISTRATION,
	REGISTRATION,
	CHECK_ACCOUNT,
	REGISTER_NEW_CONTRACT,
	SAVE_NEW_CONTRACT,
	LOG_OUT,
	CHANGE_LOCALE,
	SHOW_REQUESTS,
	POST_REQUEST,
	SHOW_ACCOUNT,
	CHANGE_PERSONAL_DETAILS,
	SET_PASSWORD,
	SET_CONTACTS,
	SHOW_TARIFFS,
	SHOW_TARIFF,
	SET_REQUEST_STATUS,
	SHOW_USERS,
	SHOW_USER,
	SUBSCRIBE,
	TO_PAYMENT,
	PAYMENT,
	SAVE_TARIFF,
	SAVE_USER,
	TO_INDEX
	}
