package by.newnet.command;

public enum CommandName {
	AUTHENTICATION, 
	REGISTRATION,
	LOG_OUT,
	CHANGE_LOCALE,
	SHOW_REQUESTS,
	POST_REQUEST,
	SHOW_ACCOUNT_INFO,
	CHANGE_PERSONAL_DETAILS,
	SET_PASSWORD,
	SET_CONTACTS,
	SHOW_TARIFFS,
	SHOW_USERS,
	SHOW_OPERATIONS,

	SUBSCRIBE,
	PAY,
	ADD_TARIFF,
	MODIFY_TARIFF,
	BLOCK_USER,
	POST_NEWS
	}
