//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.16 at 06:45:58 PM MSK 
//


package by.training.parser.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CallPrices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallPrices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="internalPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="externalPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="fixedPhonePrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallPrices", propOrder = {
    "internalPrice",
    "externalPrice",
    "fixedPhonePrice"
})
public class CallPrices {

    protected double internalPrice;
    protected double externalPrice;
    protected double fixedPhonePrice;

    /**
     * Gets the value of the internalPrice property.
     * 
     */
    public double getInternalPrice() {
        return internalPrice;
    }

    /**
     * Sets the value of the internalPrice property.
     * 
     */
    public void setInternalPrice(double value) {
        this.internalPrice = value;
    }

    /**
     * Gets the value of the externalPrice property.
     * 
     */
    public double getExternalPrice() {
        return externalPrice;
    }

    /**
     * Sets the value of the externalPrice property.
     * 
     */
    public void setExternalPrice(double value) {
        this.externalPrice = value;
    }

    /**
     * Gets the value of the fixedPhonePrice property.
     * 
     */
    public double getFixedPhonePrice() {
        return fixedPhonePrice;
    }

    /**
     * Sets the value of the fixedPhonePrice property.
     * 
     */
    public void setFixedPhonePrice(double value) {
        this.fixedPhonePrice = value;
    }

}
