//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.16 at 06:45:58 PM MSK 
//


package by.training.parser.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MobileTariff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MobileTariff">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.training.by/TariffsXMLSchema}Tariff">
 *       &lt;sequence>
 *         &lt;element name="callPrices" type="{http://www.training.by/TariffsXMLSchema}CallPrices"/>
 *         &lt;element name="smsPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="parameters" type="{http://www.training.by/TariffsXMLSchema}Parameters"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MobileTariff", propOrder = {
    "callPrices",
    "smsPrice",
    "parameters"
})
public class MobileTariff
    extends Tariff
{

    @XmlElement(required = true)
    protected CallPrices callPrices;
    @XmlElement(defaultValue = "0")
    protected double smsPrice;
    @XmlElement(required = true)
    protected Parameters parameters;

    /**
     * Gets the value of the callPrices property.
     * 
     * @return
     *     possible object is
     *     {@link CallPrices }
     *     
     */
    public CallPrices getCallPrices() {
        return callPrices;
    }

    /**
     * Sets the value of the callPrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallPrices }
     *     
     */
    public void setCallPrices(CallPrices value) {
        this.callPrices = value;
    }

    /**
     * Gets the value of the smsPrice property.
     * 
     */
    public double getSmsPrice() {
        return smsPrice;
    }

    /**
     * Sets the value of the smsPrice property.
     * 
     */
    public void setSmsPrice(double value) {
        this.smsPrice = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

}
