//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.16 at 06:45:58 PM MSK 
//


package by.training.parser.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="favouriteNumbers" type="{http://www.training.by/TariffsXMLSchema}favouriteNumbers"/>
 *         &lt;element name="addTariffFee" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="tarification" type="{http://www.training.by/TariffsXMLSchema}tarification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parameters", propOrder = {
    "favouriteNumbers",
    "addTariffFee",
    "tarification"
})
public class Parameters {

    protected int favouriteNumbers;
    protected double addTariffFee;
    protected int tarification;

    /**
     * Gets the value of the favouriteNumbers property.
     * 
     */
    public int getFavouriteNumbers() {
        return favouriteNumbers;
    }

    /**
     * Sets the value of the favouriteNumbers property.
     * 
     */
    public void setFavouriteNumbers(int value) {
        this.favouriteNumbers = value;
    }

    /**
     * Gets the value of the addTariffFee property.
     * 
     */
    public double getAddTariffFee() {
        return addTariffFee;
    }

    /**
     * Sets the value of the addTariffFee property.
     * 
     */
    public void setAddTariffFee(double value) {
        this.addTariffFee = value;
    }

    /**
     * Gets the value of the tarification property.
     * 
     */
    public int getTarification() {
        return tarification;
    }

    /**
     * Sets the value of the tarification property.
     * 
     */
    public void setTarification(int value) {
        this.tarification = value;
    }

}
