//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.16 at 06:45:58 PM MSK 
//


package by.training.parser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MobileTariff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MobileTariff">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.training.by/TariffsXMLSchema}Tariff">
 *       &lt;sequence>
 *         &lt;element name="callPrices" type="{http://www.training.by/TariffsXMLSchema}CallPrices"/>
 *         &lt;element name="smsPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="parameters" type="{http://www.training.by/TariffsXMLSchema}Parameters"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MobileTariff", propOrder = {
    "callPrices",
    "smsPrice",
    "parameters"
})
public class MobileTariff extends Tariff {

    @XmlElement(required = true)
    private CallPrices callPrices;
    @XmlElement(defaultValue = "0")
    private double smsPrice;
    @XmlElement(required = true)
    private Parameters parameters;

    public CallPrices getCallPrices() {
        return callPrices;
    }

    public void setCallPrices(CallPrices value) {
        this.callPrices = value;
    }

    public double getSmsPrice() {
        return smsPrice;
    }


    public void setSmsPrice(double value) {
        this.smsPrice = value;
    }

    
    public Parameters getParameters() {
        return parameters;
    }

    public void setParameters(Parameters value) {
        this.parameters = value;
    }

	@Override
	public String toString() {
		return super.toString() + "\n type: Mobile tariff, \n CALL PRICES: " + callPrices + ", sms price: " + smsPrice + ", \n PARAMETERS: "
		        + parameters + ".";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((callPrices == null) ? 0 : callPrices.hashCode());
		result = prime * result + ((parameters == null) ? 0 : parameters.hashCode());
		long temp;
		temp = Double.doubleToLongBits(smsPrice);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		MobileTariff other = (MobileTariff) obj;
		if (callPrices == null) {
			if (other.callPrices != null)
				return false;
		} else if (!callPrices.equals(other.callPrices))
			return false;
		if (parameters == null) {
			if (other.parameters != null)
				return false;
		} else if (!parameters.equals(other.parameters))
			return false;
		if (Double.doubleToLongBits(smsPrice) != Double.doubleToLongBits(other.smsPrice))
			return false;
		return true;
	}

}
