//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.16 at 06:45:58 PM MSK 
//


package by.training.parser.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="favouriteNumbers" type="{http://www.training.by/TariffsXMLSchema}favouriteNumbers"/>
 *         &lt;element name="addTariffFee" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="tarification" type="{http://www.training.by/TariffsXMLSchema}tarification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parameters", propOrder = {
    "favouriteNumbers",
    "addTariffFee",
    "tarification"
})
public class Parameters {

    private int favouriteNumbers;
    private double addTariffFee;
    private int tarification;

    public int getFavouriteNumbers() {
        return favouriteNumbers;
    }

    public void setFavouriteNumbers(int value) {
        this.favouriteNumbers = value;
    }

    public double getAddTariffFee() {
        return addTariffFee;
    }

    public void setAddTariffFee(double value) {
        this.addTariffFee = value;
    }

    public int getTarification() {
        return tarification;
    }

    public void setTarification(int value) {
        this.tarification = value;
    }

	@Override
	public String toString() {
		return "favourite numbers: " + favouriteNumbers + ", fee for subscribing for tariff: " + addTariffFee
		        + ", tarification starting from: " + tarification;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(addTariffFee);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + favouriteNumbers;
		result = prime * result + tarification;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Parameters other = (Parameters) obj;
		if (Double.doubleToLongBits(addTariffFee) != Double.doubleToLongBits(other.addTariffFee))
			return false;
		if (favouriteNumbers != other.favouriteNumbers)
			return false;
		if (tarification != other.tarification)
			return false;
		return true;
	}
    
}
